const fs = require('fs');
const path = require('path');
const lucide = require('lucide-react');

const dataPaths = [
  '../src/data/vocabulary-2000.json',
  '../src/data/vocabulary-a1.json',
  '../src/data/vocabulary-a2.json',
  '../src/data/vocabulary-b1.json',
  '../src/data/vocabulary-b2.json'
].map(p => path.join(__dirname, p));

const validLucideIcons = new Set(Object.keys(lucide));

const iconMap = {
  'PalmTree': 'TreePine',
  'Passport': 'BookUser',
  'Storefront': 'Store',
  'Mug': 'Coffee',
  'CalendarArrowRight': 'CalendarDays',
  'Monument': 'Landmark',
  'Tape': 'Ruler',
  'Knife': 'UtensilCrossed',
  'Tool': 'Wrench',
  'UsersX': 'UserX',
  'UserTie': 'User'
};

const usedIcons = new Set();
usedIcons.add('CircleHelp'); // Always need the fallback

// Fix data and collect used icons
dataPaths.forEach(file => {
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  data.forEach(w => {
    if (w.icon) {
      let iconName = w.icon.charAt(0).toUpperCase() + w.icon.slice(1);
      
      // Apply fallback map if invalid
      if (iconMap[iconName]) iconName = iconMap[iconName];
      if (iconMap[w.icon]) iconName = iconMap[w.icon];
      
      // Ensure it's valid, otherwise fallback
      if (validLucideIcons.has(iconName)) {
        w.icon = iconName;
      } else {
        w.icon = 'Sparkles';
        iconName = 'Sparkles';
      }
      
      usedIcons.add(iconName);
    }
  });
  
  fs.writeFileSync(file, JSON.stringify(data, null, 2));
});

const iconsArray = Array.from(usedIcons).sort();

// Handle any icon names that clash with JS reserved words (like 'Map' or 'ImageIcon')
const imports = iconsArray.map(name => {
  if (name === 'Image') return 'Image as ImageIcon';
  return name;
});

const mapEntries = iconsArray.map(name => {
  if (name === 'Image') return '  ImageIcon,';
  return `  ${name},`;
});

const tsFileContent = `import type { LucideIcon } from "lucide-react"
import {
  ${imports.join(',\n  ')}
} from "lucide-react"

/**
 * Maps icon name strings to lucide-react icon components.
 * Auto-generated by fix-icons.cjs based on vocabulary data.
 */
export const vocabIconMap: Record<string, LucideIcon> = {
${mapEntries.join('\n')}
}

/** Default fallback icon when no match is found */
export const defaultFallbackIcon = CircleHelp
`;

fs.writeFileSync(path.join(__dirname, '../src/data/vocabIconMap.ts'), tsFileContent);
console.log('Fixed icons and updated vocabIconMap.ts with', iconsArray.length, 'icons');
